### PR TITLE
Add German (formal & informal) translation

### PR DESCRIPTION
**Pull request by rfuehrer**
This pull request contains a German translation for MD. Two languages are provided: formal German ("Sie") and informal German ("Du"). I have decided to include both variants so that the user can freely choose the form of address. This means that the files and references do not follow the international codes, but distinguish the suffix "SIE" (formal) and "DU" (informal) according to the language code "de" (German).

This is the first version of a translation. German grammar sometimes requires special constellations, so that a grammatically correct sentence may require more intervention in the current logic. This is my first contact with EML, be gentle with me ;)

der certain circumstances further commits with adjustments may follow, should I have made mistakes and notice them later...

### CODE REVIEW

**Comment by Lattyware** [comment]
Thanks for the contribution! I'll take a look through as soon as I can.

On the formal/informal distinction, not something I'd considered. IETF Language Tags can contain private use subtags for cases like this, so the answer is probably to use something like `de-x-informal`/`de-x-formal` as is still a correct language tag under the spec.

If at all possible, it would probably be best to pick one to just be `de`, to make it act as the default when it comes to automatic detection from browser language. Which one of these makes most sense as a default if we don't know the user's preference isn't clear to me, so I'll defer to your wisdom on that front.

As far as the Elm logic goes, feel free to ask if you have some behaviour you need but can't implement, and I'd be happy to try and implement it if you can give the rules/some examples. Either way, I'll take a look through when I can just to make sure there aren't any other issues, and once everything is resolved we can push it in.

Thanks again for putting in the work on this!

**Comment by rfuehrer** [comment]
you are welcome :) i have seen the discussion about tags de-x-informal at other places, but i have had problems with ELM when using "-" for import. I could not name variables as desired and comprehensible. If you have a better suggestion, I am grateful for all suggestions :) At this point a note that the documentation for the translation is incomplete, I will complete the steps and information in the next step. I am convinced of your solution, this is the best implementation of the game so far!

I follow your argument with the default by the browser. That would be felt rather the formal salutation with "Sie" (references "deSIE", "GermanSie"). In a private context, perhaps the "you" will prevail, which is closer to the character of the game. But this can be freely adjusted by the user.

Where is the default set: as "code" in the deSIE.eml?

**Comment by Lattyware** [comment]
Yeah, the Elm name doesn't matter so much. In general I've been following the pattern of removing the dashes and using capitals to indicate the breaks, so `de-x-formal` would become `DeXFormal`. The important one is the `code` value in the `pack` value, which is a string so the value with the dashes should be fine. This is the one that will be compared to browser language tags when picking a language, and so it is important it follows the spec.

So the process is essentially the browser will list a set of language codes the user is looking for (e.g; for me `en-GB`, `en` and `en-US`) and the game will pick the first one that is a perfect match, and then fall back to trying to find the best partial match.

So if you make the one that should be the default `De.elm` and use the `code` `"de"`, and then the other one can be `DeXInformal.elm`/`DeXFormal.elm` with the `code` `de-x-informal`/`de-x-formal` (depending on which one you chose to be the default). This way if a user's browser says they are using the `de` language, it will match the default and use it by default, but the user can then select the other variant.

**Comment by rfuehrer** [comment]
Default was defined to formal language and the informal variant is optional

**Comment by Lattyware** [comment]
Looks good. I'll try and merge it through as soon as I get the chance if you are happy with it (obviously you can still submit new PRs with corrections in the future if needed).

**Comment by Lattyware** [comment]
Just as a heads-up, it looks like you have accidentally pushed some changes you made for testing ([`docker-build.sh`](https://github.com/Lattyware/massivedecks/pull/161/commits/04d47169d539fced4755c1e26e10194722c28867#diff-1e5c4882847e3eefa76de60a300139b8) and changes to [`docker-compose.yml`](https://github.com/Lattyware/massivedecks/pull/161/commits/04d47169d539fced4755c1e26e10194722c28867#diff-4e5e90c6228fd48698d074241c2ba760)).

**Comment by rfuehrer** [comment]
Melissa, a colleague from work, has found some bugs, which i'm going to update right now. i'll take out the superfluous files. unfortunately i was blinded by my work...

**Comment by Lattyware** [comment]
Sorry for the delay getting this in. Merged with a very very minor changes as of 4670403b60e004fffe1c757edbc347ffa2b8604c.

Thanks for the contribution!
.

**Pull request closed without merging**
