### PR TITLE
Translate missing Polish strings

### PR DESCRIPTION
**Pull request by TheChilliPL**

### CODE REVIEW

**Comment by Lattyware** [comment]
Thanks for the update, looks good. I'll merge this though as soon as I get a chance.

**Comment by TheChilliPL** [comment]
I noticed some small mistake in the already existing string so I'll try to fix that

**Comment by TheChilliPL** [comment]
Fixed some mistakes I found while playing (related to numbers being declinable)

**Comment by Lattyware** [comment]
This has been merged in as de7a09ce5b565b97f7377abff5328f869096dccb, thanks for the contribution and apologies for the delay in getting it merged in.

**Comment by TheChilliPL** [comment]
Not a problem, glad to have been able to contribute!

**Pull request closed without merging**
